version: '3'

services:
# database
  ddb: # django database
    container_name: pm_ddb
    image: mysql:latest
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password

  auth:
    container_name: pm_auth
    image: django-app
    volumes:
      - ./backend/users/:/app/users
    working_dir: /app/users
    command: bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -w 3 users.wsgi:application"
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    depends_on:
      - pm_ddb

  notif:
    container_name: pm_notif
    image: django-app
    volumes:
      - ./backend/notifications:/app/notifications
    working_dir: /app/notifications
    command: bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8001 -w 3 notifications.wsgi:application"
    # ports:
    #   - 8001:8001
    expose:
      - 8001
    depends_on:
      - pm_ddb

  dlb: #django proxy
    image: nginx:latest
    restart: always # restart on reboot
    volumes:
      - ./proxy-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/web/build:/app
    ports:
      - '8080:80' # 8080 for outer OPS (operating system) localhost 80 for inner
    depends_on:
      - auth
      - notif
      - pm_ddb
